version: '2'

services:
  server:
    build:
      context: . 
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: web_server
    ports:
      - "3003:3003"

  db:
    image: mongo:latest
    container_name: db
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod

volumes:
  mongodb: